version: '3.1'

services:

  mysql:
    image: 'mysql:latest'

    restart: always
    container_name: containerstore

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: online_store
    ports:
      - '5000:3306'
    networks:
      - networkstore


  online_store:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8090:8090'
    depends_on:
      - mysql
    networks:
      - networkstore


networks:
  networkstore:
    driver: bridge
